// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210906062941_UserWatchList")]
    partial class UserWatchList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.DefaultItemDetails", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("examine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("highalch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("limit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("lowalch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("members")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mostRecentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("prediction")
                        .HasColumnType("INTEGER");

                    b.Property<long>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("mostRecentSnapshotId");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("Domain.ItemHistorical", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemHistoricals");
                });

            modelBuilder.Entity("Domain.ItemPriceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ItemHistoricalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("high")
                        .HasColumnType("INTEGER");

                    b.Property<long>("highTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("low")
                        .HasColumnType("INTEGER");

                    b.Property<long>("lowTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemHistoricalId");

                    b.ToTable("ItemPriceSnapshots");
                });

            modelBuilder.Entity("Domain.UserWatchList", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MostRecentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WatchListItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "ItemDetailsId");

                    b.HasIndex("ItemDetailsId");

                    b.HasIndex("MostRecentSnapshotId");

                    b.HasIndex("WatchListItemDetailsId");

                    b.ToTable("UserWatchList");
                });

            modelBuilder.Entity("Domain.WatchListItemDetails", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("examine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("highalch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("limit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("lowalch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("members")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mostRecentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("prediction")
                        .HasColumnType("INTEGER");

                    b.Property<long>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("mostRecentSnapshotId");

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.DefaultItemDetails", b =>
                {
                    b.HasOne("Domain.ItemPriceSnapshot", "mostRecentSnapshot")
                        .WithMany()
                        .HasForeignKey("mostRecentSnapshotId");

                    b.Navigation("mostRecentSnapshot");
                });

            modelBuilder.Entity("Domain.ItemPriceSnapshot", b =>
                {
                    b.HasOne("Domain.ItemHistorical", null)
                        .WithMany("historical")
                        .HasForeignKey("ItemHistoricalId");
                });

            modelBuilder.Entity("Domain.UserWatchList", b =>
                {
                    b.HasOne("Domain.AppUser", "AppUser")
                        .WithMany("UserWatchList")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DefaultItemDetails", "ItemDetails")
                        .WithMany("UserWatchList")
                        .HasForeignKey("ItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ItemPriceSnapshot", "MostRecentSnapshot")
                        .WithMany()
                        .HasForeignKey("MostRecentSnapshotId");

                    b.HasOne("Domain.WatchListItemDetails", null)
                        .WithMany("UserWatchList")
                        .HasForeignKey("WatchListItemDetailsId");

                    b.Navigation("AppUser");

                    b.Navigation("ItemDetails");

                    b.Navigation("MostRecentSnapshot");
                });

            modelBuilder.Entity("Domain.WatchListItemDetails", b =>
                {
                    b.HasOne("Domain.ItemPriceSnapshot", "mostRecentSnapshot")
                        .WithMany()
                        .HasForeignKey("mostRecentSnapshotId");

                    b.Navigation("mostRecentSnapshot");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Navigation("UserWatchList");
                });

            modelBuilder.Entity("Domain.DefaultItemDetails", b =>
                {
                    b.Navigation("UserWatchList");
                });

            modelBuilder.Entity("Domain.ItemHistorical", b =>
                {
                    b.Navigation("historical");
                });

            modelBuilder.Entity("Domain.WatchListItemDetails", b =>
                {
                    b.Navigation("UserWatchList");
                });
#pragma warning restore 612, 618
        }
    }
}
